/**
 * Login Page Handler
 *
 * Route: GET /login?tenant={tenantId}&redirect={returnUrl}
 *
 * Renders a branded login page with:
 * - Email + password form
 * - OAuth buttons (Google)
 * - "Forgot password?" link
 * - "Don't have an account? Sign up" link
 *
 * English-only in this phase. Multi-locale auth pages deferred
 * until auth UI is stable.
 */
import type { Env } from '../types.js';
import { loadTenantBranding } from '../branding.js';
import { renderAuthPage, type BackLink, oauthIcons, escapeHtml, escapeAttr } from './renderer.js';
import { isAdminDomain } from '../security/platformDomains.js';
import { validateRedirectUrl } from '../security/redirectValidator.js';

/**
 * Handle GET /login — render the branded login page.
 */
export async function handleLoginPage(request: Request, env: Env): Promise<Response> {
  const url = new URL(request.url);
  const tenant = url.searchParams.get('tenant');
  // Accept both 'redirect' (storefront) and 'redirect_uri' (admin SPA)
  const redirect = url.searchParams.get('redirect') || url.searchParams.get('redirect_uri') || '';
  const error = url.searchParams.get('error');
  const message = url.searchParams.get('message');
  // PKCE params from admin SPA — pass through to form/OAuth
  const audience = url.searchParams.get('audience') || '';
  const codeChallenge = url.searchParams.get('code_challenge') || '';
  const codeChallengeMethod = url.searchParams.get('code_challenge_method') || '';
  // Server-side PKCE session reference (.com bounce-tracking workaround).
  const pkceSession = url.searchParams.get('pkce_session') || '';

  // Stale-bookmark guard.
  //
  // An admin-audience login URL with a code_challenge but no pkce_session
  // can only have been generated by a pre-fix build of the hub SPA — fresh
  // login() calls always include pkce_session. The URL itself is unusable:
  // the OAuth state row gets stored with pkce_session_id = NULL, the
  // callback comes back without the session id, and the SPA's Callback
  // refuses to proceed. Send the user to the SPA root so the new login()
  // can regenerate everything cleanly.
  if (audience === 'admin' && codeChallenge && !pkceSession && redirect) {
    try {
      const redirectOrigin = new URL(redirect).origin;
      const redirectHostname = new URL(redirect).hostname;
      if (isAdminDomain(redirectHostname)) {
        return new Response(null, {
          status: 302,
          headers: {
            Location: redirectOrigin,
            'Cache-Control': 'no-store',
          },
        });
      }
    } catch {
      // Invalid redirect — fall through to normal rendering, which will
      // surface an error to the user.
    }
  }

  const branding = await loadTenantBranding(tenant, env);

  // Build an optional back-link for storefront redirects.
  // Only shown when the redirect is a validated tenant origin (not admin console).
  // Per AI_RULES §centerpiece-auth: every redirect-producing code path runs through
  // redirectValidator before constructing URLs derived from user-supplied input.
  let backLink: BackLink | undefined;
  if (redirect && audience !== 'admin') {
    try {
      const validated = await validateRedirectUrl(redirect, env.TENANT_CONFIGS, env.ENVIRONMENT);
      if (validated.valid) {
        const redirectHostname = new URL(redirect).hostname;
        if (!isAdminDomain(redirectHostname)) {
          backLink = {
            href: validated.origin,
            label: `Back to ${branding.storeName}`,
          };
        }
      }
    } catch {
      // Invalid redirect URL — back-link omitted; auth flow continues normally.
    }
  }

  // Build OAuth URLs — include PKCE params so they flow through the OAuth state
  const oauthBase = `${env.AUTH_DOMAIN}/oauth`;
  const oauthParams = buildOAuthParams(tenant, redirect, audience, codeChallenge, codeChallengeMethod, pkceSession);

  const body = `
    <h1 class="auth-card__title">Sign In</h1>
    <p class="auth-card__subtitle">Welcome back. Sign in to your account.</p>

    ${message ? `<div class="auth-success" data-visible="true">${escapeHtml(getSuccessMessage(message))}</div>` : ''}
    ${error ? `<div class="auth-error" data-visible="true">${escapeHtml(getErrorMessage(error))}</div>` : '<div class="auth-error" id="auth-error"></div>'}

    <form class="auth-form" method="POST" action="${escapeAttr(env.AUTH_DOMAIN)}/api/login" id="login-form">
      <input type="hidden" name="tenant" value="${escapeAttr(tenant || '')}">
      <input type="hidden" name="redirect" value="${escapeAttr(redirect)}">
      ${audience ? `<input type="hidden" name="audience" value="${escapeAttr(audience)}">` : ''}
      ${codeChallenge ? `<input type="hidden" name="code_challenge" value="${escapeAttr(codeChallenge)}">` : ''}
      ${codeChallengeMethod ? `<input type="hidden" name="code_challenge_method" value="${escapeAttr(codeChallengeMethod)}">` : ''}
      ${pkceSession ? `<input type="hidden" name="pkce_session" value="${escapeAttr(pkceSession)}">` : ''}

      <div class="form-group">
        <label class="form-label" for="email">Email</label>
        <input class="form-input" type="email" id="email" name="email" placeholder="you@example.com" required autocomplete="email" autofocus>
      </div>

      <div class="form-group">
        <label class="form-label" for="password">Password</label>
        <input class="form-input" type="password" id="password" name="password" placeholder="Enter your password" required autocomplete="current-password" minlength="8">
      </div>

      <div class="auth-forgot">
        <a class="auth-link" href="${escapeAttr(env.AUTH_DOMAIN)}/reset-password?tenant=${encodeURIComponent(tenant || '')}&redirect=${encodeURIComponent(redirect)}">Forgot password?</a>
      </div>

      <div class="form-group form-group--checkbox">
        <label class="form-label form-label--checkbox">
          <input type="checkbox" name="remember_device" id="remember_device" value="1">
          Remember this device for 90 days
        </label>
      </div>

      <button class="btn-primary" type="submit">Sign In</button>
    </form>

    <div class="auth-divider">
      <span class="auth-divider__text">or</span>
    </div>

    <div class="oauth-buttons" id="oauth-buttons">
      <a class="btn-oauth" id="oauth-google" href="${escapeAttr(oauthBase)}/google?${oauthParams}">
        ${oauthIcons.google}
        Continue with Google
      </a>
    </div>

    <script>
      (function () {
        var cb = document.getElementById('remember_device');
        var buttons = document.querySelectorAll('#oauth-buttons .btn-oauth');
        buttons.forEach(function (btn) {
          btn.addEventListener('click', function (e) {
            if (cb && cb.checked) {
              e.preventDefault();
              var href = btn.getAttribute('href');
              var sep = href.indexOf('?') !== -1 ? '&' : '?';
              window.location.href = href + sep + 'remember_device=1';
            }
          });
        });
      })();
    </script>

    <p class="auth-footer-link">
      Don't have an account?
      <a class="auth-link" href="${escapeAttr(env.AUTH_DOMAIN)}/register?tenant=${encodeURIComponent(tenant || '')}&redirect=${encodeURIComponent(redirect)}${audience ? '&audience=' + encodeURIComponent(audience) : ''}${codeChallenge ? '&code_challenge=' + encodeURIComponent(codeChallenge) : ''}${codeChallengeMethod ? '&code_challenge_method=' + encodeURIComponent(codeChallengeMethod) : ''}${pkceSession ? '&pkce_session=' + encodeURIComponent(pkceSession) : ''}">Sign up</a>
    </p>
  `;

  const html = renderAuthPage(branding, { title: 'Sign In', body }, env.PLATFORM_DOMAIN, backLink);

  return new Response(html, {
    status: 200,
    headers: {
      'Content-Type': 'text/html; charset=utf-8',
      'Cache-Control': 'no-store',
      'X-Content-Type-Options': 'nosniff',
      'X-Frame-Options': 'DENY',
      'Referrer-Policy': 'strict-origin-when-cross-origin',
    },
  });
}

// ─── Helpers ────────────────────────────────────────────────

function buildOAuthParams(
  tenant: string | null,
  redirect: string,
  audience: string,
  codeChallenge: string,
  codeChallengeMethod: string,
  pkceSession: string
): string {
  const params = new URLSearchParams();
  if (tenant) params.set('tenant', tenant);
  if (redirect) params.set('redirect', redirect);
  if (audience) params.set('audience', audience);
  if (codeChallenge) params.set('code_challenge', codeChallenge);
  if (codeChallengeMethod) params.set('code_challenge_method', codeChallengeMethod);
  if (pkceSession) params.set('pkce_session', pkceSession);
  return params.toString();
}

/**
 * Map success message codes to user-facing messages.
 */
function getSuccessMessage(code: string): string {
  switch (code) {
    case 'reset_sent':
      return 'If that email is registered, we sent a password reset link. Check your inbox.';
    case 'password_changed':
      return 'Your password has been changed successfully. Please sign in.';
    default:
      return '';
  }
}

/**
 * Map error codes to user-facing messages.
 * Account enumeration prevention: never reveal whether an email exists.
 */
function getErrorMessage(code: string): string {
  switch (code) {
    case 'invalid_credentials':
      return 'Invalid email or password.';
    case 'account_locked':
      return 'This account has been temporarily locked. Please try again later.';
    case 'session_expired':
      return 'Your session has expired. Please sign in again.';
    case 'oauth_failed':
      return 'Authentication with the provider failed. Please try again.';
    case 'oauth_not_configured':
      return 'Social login is not available for this provider. Please use email and password instead.';
    case 'invalid_redirect':
      return 'The return URL is not valid. Please try again from the store.';
    default:
      return 'An error occurred. Please try again.';
  }
}
